compatibility:
  # Inference tags for direct compatibility
  inference_tags:
    - "text-generation-inference"
    - "text-embeddings-inference"
  
  # Transformers library compatible pipelines
  transformers_pipelines:
    - "text-classification"
    - "text-generation"
  
  # Diffusers library compatible pipelines
  diffusers_pipelines:
    - "diffusers:FluxPipeline"
    - "diffusers:IFPipeline"
    - "diffusers:KandinskyPipeline"
    - "diffusers:KandinskyV22Pipeline"
    - "diffusers:StableDiffusionControlNetPipeline"
    - "diffusers:StableDiffusionPipeline"
    - "diffusers:StableDiffusionXLPipeline"
  
  # Diffusers library compatible tasks
  diffusers_tasks:
    - "text-to-image"