default_limit: 5
scenarios:
  most_used_per_inf_solution:
    sort: "downloads"
    direction: -1
    tags:
      - "text-generation-inference,finance"
      - "text-embeddings-inference,finance"
  most_trending_per_inf_solution:
    sort: "trendingScore"
    direction: -1
    tags:
      - "text-generation-inference,finance"
      - "text-embeddings-inference,finance"