industries:
  finance:
    tags: []  # placeholder
    tasks:
      - "text-classification"
      - "text-generation"
    use_cases: []  # placeholder
  healthcare:
    tags: []  # placeholder
    tasks: []  # placeholder
    use_cases: []  # placeholder
  retail:
    tags: []  # placeholder
    tasks: []  # placeholder
    use_cases: []  # placeholder 