default_limit: 10
scenarios:
  all_trending:
    sort: "trendingScore"
    direction: -1
  trending_per_task:
    sort: "trendingScore"
    direction: -1
    tasks:
      - "text-generation"
      - "text-classification"
      - "text-to-image"
      - "text-image-to-image"
      - "text-to-speech"
      - "sentence-similarity"
      - "feature-extraction"
  all_most_used:
    sort: "downloads"
    direction: -1
  most_used_per_task:
    sort: "downloads"
    direction: -1
    tasks:
      - "text-generation"
      - "text-to-image"
      - "text-image-to-image"
      - "text-to-speech"
      - "sentence-similarity"
      - "feature-extraction"