default_limit: 40
scenarios:
  most_used_per_inf_solution:
    sort: "downloads"
    direction: -1
    tags:
      - "text-generation-inference"
      - "text-embeddings-inference"
  most_trending_per_inf_solution:
    sort: "trendingScore"
    direction: -1
    tags:
      - "text-generation-inference"
      - "text-embeddings-inference"